description: "Python project base conventions"
extends:
  - self::base/base
modules:
  - self::python/style
  - self::python/venv
  - self::python/dependencies/base
  - self::python/testing/base
  - self::python/testing/pytest
  - self::python/build
