description: "Python project base conventions"
extends:
  - haondt::base/base
modules:
  - haondt::python/style
  - haondt::python/venv
  - haondt::python/dependencies/base
  - haondt::python/testing/base
  - haondt::python/testing/pytest
  - haondt::python/build
